# Site settings
title: My First Blog
email: pughbt@miamioh.edu
description: > 
    This is my first attempt to build a static site using Jekyll. This is the first step into the larger world of website building for me.
baseurl: "/pughblog" # the subpath of your site, e.g. /blog
url: "localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: pughblog
github_username:  pughbt 

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

